language: go
go:
    - 1.16.x
go_import_path: github.com/cellcycle/go-web3
sudo: false
before_install:
    - sudo apt-get install software-properties-common -y -qq
    - sudo add-apt-repository -y ppa:ethereum/ethereum
    - sudo apt-get update -qq
install:
    - sudo apt-get install ethereum -y -qq
before_script:
    - geth --dev --ws --ws.origins="*" --rpc --rpcapi admin,debug,web3,eth,txpool,personal,clique,miner,net --mine --allow-insecure-unlock &
    - sleep 5
script:
    - go mod tidy
    - go mod download
    - go mod vendor
    - go test -v ./test/...
